# Generated by Django 5.2.1 on 2025-05-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
        ),
    ]
