# Generated by Django 5.2.1 on 2025-06-03 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('queryText', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responseText', models.TextField(blank=True, null=True)),
                ('session_id', models.ForeignKey(db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='usersession.usersession')),
            ],
        ),
    ]
