# Generated by Django 4.2.7 on 2025-05-30 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chatID', models.IntegerField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('queryText', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responseText', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
