# Generated by Django 5.2.1 on 2025-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
