# Generated by Django 5.2.1 on 2025-06-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_chatid'),
        ('usersession', '0002_remove_usersession_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='usersession.usersession'),
        ),
    ]
