# Generated by Django 5.2.1 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
