# Generated by Django 5.2.1 on 2025-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_chatid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='endTime',
            field=models.DateTimeField(),
        ),
    ]
