# Generated by Django 4.2.7 on 2025-05-30 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSession',
            fields=[
                ('session_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(editable=False, verbose_name=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True)),
                ('chat_id', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='chat.chat')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='Users.users')),
            ],
        ),
    ]
