# Generated by Django 5.2.1 on 2025-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
