# Generated by Django 5.2.1 on 2025-06-03 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('docid', models.AutoField(primary_key=True, serialize=False)),
                ('patentNumber', models.CharField(max_length=20)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('documentPath', models.FileField(help_text='Only PDF files are allowed', upload_to='documents/patents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
