# Generated by Django 4.2.7 on 2025-05-30 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('docid', models.IntegerField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('patentNumber', models.CharField(max_length=20)),
                ('uploadTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('documentPath', models.CharField(max_length=300)),
            ],
        ),
    ]
